@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
POST http://{{host}}/api/drink HTTP/1.1
Content-Type: application/json

{
    "name": "testdrink1",
    "tags": ["tag1","tag2"]
}
###
PUT http://{{host}}/api/drink HTTP/1.1
Content-Type: application/json

{
    "name": "testdrink1",
    "tags": ["spisy,tag2"]
}
###
GET http://{{host}}/api/drink/id/0
### 
POST http://{{host}}/api/user HTTP/1.1
Content-Type: application/json

{
    "username":"testuser1",
    "password":"testpassword1",
    "drinknames":["testdrink1","testdrink2"]
}
###
GET http://{{host}}/api/user/2 HTTP/1.1
Content-Type: application/json
###
GET http://{{host}}/api/user/1 HTTP/1.1
Content-Type: application/json
###
PATCH  http://{{host}}/api/user/fav HTTP/1.1
Content-Type: application/json

{
    "id": 1, 
    "drinkname": "testdrink1"
}